# This tells Chimera how to load in the precondition functions class in order to do the input preprocessor step.
preprocessor:
  # module_path is a path to where the given class can be found
  module_path: opera_chimera.precondition_functions

  # class_name must be a subclass of Chimera's PreConditionFunctions class.
  class_name: OperaPreConditionFunctions

# This tells Chimera how to load in the job submitter class in order to do the PGE job submission step.
job_submitter:
  # module_path is a path to where the given class can be found
  module_path: opera_chimera.opera_pge_job_submitter

  # class_name must be a subclass of Chimera's PgeJobSubmitter class.
  class_name: OperaPgeJobSubmitter

# This tells Chimera how to load in the post processor class in order to run any custom post processing.
postprocessor:
  # module_path is a path to where the given class can be found
  module_path: opera_chimera.postprocess_functions

  # class_name must be a subclass of Chimera's PostProcessFunctions class.
  class_name: OperaPostProcessFunctions
